[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://taffojeuixiqroyferps.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_xEEdmWUfowt-VHM44GIKZA_j43eGqAo"
  NEXT_PUBLIC_SUPABASE_STORAGE_BUCKET = "tenant-media"
