/**
 * Audit actions. Kept in a client-safe module (no `server-only`) because the
 * Super Admin's audit filters render them in the browser, while the writers in
 * `log.ts` consume the same constant.
 */
export const AUDIT_ACTIONS = {
  businessCreated: "business.created",
  businessUpdated: "business.updated",
  businessSuspended: "business.suspended",
  businessReactivated: "business.reactivated",
  businessArchived: "business.archived",
  businessDeleted: "business.deleted",
  subscriptionCreated: "subscription.created",
  subscriptionRenewed: "subscription.renewed",
  subscriptionUpdated: "subscription.updated",
  subscriptionCancelled: "subscription.cancelled",
  userCreated: "user.created",
  userUpdated: "user.updated",
  userDisabled: "user.disabled",
  userEnabled: "user.enabled",
  roleChanged: "user.role_changed",
  permissionsChanged: "user.permissions_changed",
  passwordResetInitiated: "auth.password_reset_initiated",
  passwordChanged: "auth.password_changed",
  impersonationStarted: "support.impersonation_started",
  impersonationEnded: "support.impersonation_ended",
  categoryCreated: "catalog.category_created",
  categoryUpdated: "catalog.category_updated",
  categoryDeleted: "catalog.category_deleted",
  categoryReordered: "catalog.categories_reordered",
  itemCreated: "catalog.item_created",
  itemUpdated: "catalog.item_updated",
  itemDeleted: "catalog.item_deleted",
  itemBulkUpdated: "catalog.items_bulk_updated",
  priceChanged: "catalog.price_changed",
  stockChanged: "catalog.stock_changed",
  modifierGroupChanged: "catalog.modifier_group_changed",
  offerCreated: "offers.created",
  offerUpdated: "offers.updated",
  offerDeleted: "offers.deleted",
  brandingChanged: "settings.branding_changed",
  settingsChanged: "settings.changed",
  branchCreated: "branches.created",
  branchUpdated: "branches.updated",
  branchDeleted: "branches.deleted",
  mediaUploaded: "media.uploaded",
  mediaDeleted: "media.deleted",
  translationUpdated: "translations.updated",
  translationJobStarted: "translations.job_started",
  planChanged: "platform.plan_changed",
  platformSettingChanged: "platform.setting_changed",
  featureFlagChanged: "platform.feature_flag_changed",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
