// AUTO-GENERATED by `npm run db:types`. Do not edit by hand.
// Source of truth: supabase/migrations/*.sql

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type AccountStatus = "active" | "suspended" | "archived";
export type AnalyticsEventType =
  | "menu_view"
  | "category_view"
  | "item_view"
  | "search"
  | "language_change"
  | "offer_view"
  | "branch_view";
export type BusinessType =
  "restaurant" | "cafe" | "salon" | "barbershop" | "custom";
export type DiscountType = "percentage" | "fixed_amount" | "promotional_price";
export type MediaKind = "image" | "logo" | "icon" | "gallery" | "document";
export type MembershipStatus = "invited" | "active" | "disabled";
export type ModifierSelection = "single" | "multiple";
export type OfferTargetType = "item" | "category" | "branch" | "all_items";
export type PlatformRole = "super_admin" | "support" | "analyst";
export type SubscriptionStatus =
  "trial" | "active" | "expiring_soon" | "expired" | "suspended" | "cancelled";
export type TranslationJobStatus =
  "queued" | "running" | "completed" | "failed" | "cancelled";
export type TranslationStatus =
  "draft" | "ai_generated" | "reviewed" | "approved";

export type Database = {
  public: {
    Tables: {
      analytics_events: {
        Row: {
          id: number;
          tenant_id: string;
          branch_id: string | null;
          event_type: AnalyticsEventType;
          category_id: string | null;
          item_id: string | null;
          offer_id: string | null;
          session_hash: string | null;
          locale: string | null;
          search_query: string | null;
          search_results_count: number | null;
          device_type: string | null;
          referrer_host: string | null;
          occurred_at: string;
          created_at: string;
        };
        Insert: {
          id?: number;
          tenant_id: string;
          branch_id?: string | null;
          event_type: AnalyticsEventType;
          category_id?: string | null;
          item_id?: string | null;
          offer_id?: string | null;
          session_hash?: string | null;
          locale?: string | null;
          search_query?: string | null;
          search_results_count?: number | null;
          device_type?: string | null;
          referrer_host?: string | null;
          occurred_at?: string;
          created_at?: string;
        };
        Update: {
          id?: number;
          tenant_id?: string;
          branch_id?: string | null;
          event_type?: AnalyticsEventType;
          category_id?: string | null;
          item_id?: string | null;
          offer_id?: string | null;
          session_hash?: string | null;
          locale?: string | null;
          search_query?: string | null;
          search_results_count?: number | null;
          device_type?: string | null;
          referrer_host?: string | null;
          occurred_at?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "analytics_events_branch_id_fkey";
            columns: ["branch_id"];
            isOneToOne: false;
            referencedRelation: "branches";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "analytics_events_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "analytics_events_item_id_fkey";
            columns: ["item_id"];
            isOneToOne: false;
            referencedRelation: "items";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "analytics_events_offer_id_fkey";
            columns: ["offer_id"];
            isOneToOne: false;
            referencedRelation: "offers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "analytics_events_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
        ];
      };
      audit_logs: {
        Row: {
          id: number;
          tenant_id: string | null;
          actor_user_id: string | null;
          actor_type: string;
          actor_email: string | null;
          actor_label: string;
          action: string;
          entity_type: string;
          entity_id: string | null;
          previous_values: Json | null;
          new_values: Json | null;
          metadata: Json;
          ip_address: string | null;
          user_agent: string | null;
          is_impersonated: boolean;
          impersonated_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: number;
          tenant_id?: string | null;
          actor_user_id?: string | null;
          actor_type?: string;
          actor_email?: string | null;
          actor_label?: string;
          action: string;
          entity_type: string;
          entity_id?: string | null;
          previous_values?: Json | null;
          new_values?: Json | null;
          metadata?: Json;
          ip_address?: string | null;
          user_agent?: string | null;
          is_impersonated?: boolean;
          impersonated_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          tenant_id?: string | null;
          actor_user_id?: string | null;
          actor_type?: string;
          actor_email?: string | null;
          actor_label?: string;
          action?: string;
          entity_type?: string;
          entity_id?: string | null;
          previous_values?: Json | null;
          new_values?: Json | null;
          metadata?: Json;
          ip_address?: string | null;
          user_agent?: string | null;
          is_impersonated?: boolean;
          impersonated_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "audit_logs_actor_user_id_fkey";
            columns: ["actor_user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "audit_logs_impersonated_by_fkey";
            columns: ["impersonated_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "audit_logs_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
        ];
      };
      branches: {
        Row: {
          id: string;
          public_id: string;
          tenant_id: string;
          slug: string;
          name: string;
          address_line: string;
          city: string;
          country: string;
          phone: string | null;
          whatsapp: string | null;
          email: string | null;
          latitude: number | null;
          longitude: number | null;
          timezone: string;
          opening_hours: Json;
          public_menu_code: string;
          qr_target_url: string | null;
          allow_branch_prices: boolean;
          is_active: boolean;
          display_order: number;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          public_id?: string;
          tenant_id: string;
          slug: string;
          name: string;
          address_line?: string;
          city?: string;
          country?: string;
          phone?: string | null;
          whatsapp?: string | null;
          email?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          timezone?: string;
          opening_hours?: Json;
          public_menu_code?: string;
          qr_target_url?: string | null;
          allow_branch_prices?: boolean;
          is_active?: boolean;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          public_id?: string;
          tenant_id?: string;
          slug?: string;
          name?: string;
          address_line?: string;
          city?: string;
          country?: string;
          phone?: string | null;
          whatsapp?: string | null;
          email?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          timezone?: string;
          opening_hours?: Json;
          public_menu_code?: string;
          qr_target_url?: string | null;
          allow_branch_prices?: boolean;
          is_active?: boolean;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "branches_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
        ];
      };
      business_settings: {
        Row: {
          tenant_id: string;
          primary_color: string;
          secondary_color: string;
          accent_color: string;
          background_color: string;
          font_family: string;
          price_display_format: string;
          show_prices: boolean;
          tax_display: string;
          tax_rate: number;
          tax_label: string;
          enabled_item_fields: Json;
          terminology_overrides: Json;
          social_links: Json;
          contact_overrides: Json;
          ai_translation_enabled: boolean;
          require_translation_approval: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          tenant_id: string;
          primary_color?: string;
          secondary_color?: string;
          accent_color?: string;
          background_color?: string;
          font_family?: string;
          price_display_format?: string;
          show_prices?: boolean;
          tax_display?: string;
          tax_rate?: number;
          tax_label?: string;
          enabled_item_fields?: Json;
          terminology_overrides?: Json;
          social_links?: Json;
          contact_overrides?: Json;
          ai_translation_enabled?: boolean;
          require_translation_approval?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          tenant_id?: string;
          primary_color?: string;
          secondary_color?: string;
          accent_color?: string;
          background_color?: string;
          font_family?: string;
          price_display_format?: string;
          show_prices?: boolean;
          tax_display?: string;
          tax_rate?: number;
          tax_label?: string;
          enabled_item_fields?: Json;
          terminology_overrides?: Json;
          social_links?: Json;
          contact_overrides?: Json;
          ai_translation_enabled?: boolean;
          require_translation_approval?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "business_settings_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: true;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
        ];
      };
      business_templates: {
        Row: {
          id: string;
          code: string;
          business_type: BusinessType;
          name: string;
          description: string;
          icon: string;
          terminology: Json;
          enabled_item_fields: Json;
          default_categories: Json;
          default_modifier_groups: Json;
          default_feature_flags: Json;
          is_active: boolean;
          is_system: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          code: string;
          business_type: BusinessType;
          name: string;
          description?: string;
          icon?: string;
          terminology?: Json;
          enabled_item_fields?: Json;
          default_categories?: Json;
          default_modifier_groups?: Json;
          default_feature_flags?: Json;
          is_active?: boolean;
          is_system?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          code?: string;
          business_type?: BusinessType;
          name?: string;
          description?: string;
          icon?: string;
          terminology?: Json;
          enabled_item_fields?: Json;
          default_categories?: Json;
          default_modifier_groups?: Json;
          default_feature_flags?: Json;
          is_active?: boolean;
          is_system?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      categories: {
        Row: {
          id: string;
          public_id: string;
          tenant_id: string;
          parent_id: string | null;
          slug: string;
          image_path: string | null;
          image_url: string | null;
          icon: string | null;
          color: string | null;
          display_order: number;
          is_active: boolean;
          visible_from: string | null;
          visible_until: string | null;
          visibility_schedule: Json | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          public_id?: string;
          tenant_id: string;
          parent_id?: string | null;
          slug: string;
          image_path?: string | null;
          image_url?: string | null;
          icon?: string | null;
          color?: string | null;
          display_order?: number;
          is_active?: boolean;
          visible_from?: string | null;
          visible_until?: string | null;
          visibility_schedule?: Json | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          public_id?: string;
          tenant_id?: string;
          parent_id?: string | null;
          slug?: string;
          image_path?: string | null;
          image_url?: string | null;
          icon?: string | null;
          color?: string | null;
          display_order?: number;
          is_active?: boolean;
          visible_from?: string | null;
          visible_until?: string | null;
          visibility_schedule?: Json | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "categories_parent_id_fkey";
            columns: ["parent_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "categories_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
        ];
      };
      category_branches: {
        Row: {
          tenant_id: string;
          category_id: string;
          branch_id: string;
        };
        Insert: {
          tenant_id: string;
          category_id: string;
          branch_id: string;
        };
        Update: {
          tenant_id?: string;
          category_id?: string;
          branch_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "category_branches_branch_id_fkey";
            columns: ["branch_id"];
            isOneToOne: false;
            referencedRelation: "branches";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "category_branches_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "category_branches_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
        ];
      };
      category_translations: {
        Row: {
          id: string;
          tenant_id: string;
          category_id: string;
          locale: string;
          name: string;
          description: string;
          status: TranslationStatus;
          is_machine_generated: boolean;
          approved_at: string | null;
          approved_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          category_id: string;
          locale: string;
          name?: string;
          description?: string;
          status?: TranslationStatus;
          is_machine_generated?: boolean;
          approved_at?: string | null;
          approved_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          category_id?: string;
          locale?: string;
          name?: string;
          description?: string;
          status?: TranslationStatus;
          is_machine_generated?: boolean;
          approved_at?: string | null;
          approved_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "category_translations_approved_by_fkey";
            columns: ["approved_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "category_translations_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "category_translations_locale_fkey";
            columns: ["locale"];
            isOneToOne: false;
            referencedRelation: "languages";
            referencedColumns: ["code"];
          },
          {
            foreignKeyName: "category_translations_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
        ];
      };
      currencies: {
        Row: {
          code: string;
          name: string;
          symbol: string;
          decimal_digits: number;
          is_enabled: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          code: string;
          name: string;
          symbol: string;
          decimal_digits?: number;
          is_enabled?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          code?: string;
          name?: string;
          symbol?: string;
          decimal_digits?: number;
          is_enabled?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      feature_flags: {
        Row: {
          key: string;
          name: string;
          description: string;
          default_enabled: boolean;
          is_tenant_overridable: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          key: string;
          name: string;
          description?: string;
          default_enabled?: boolean;
          is_tenant_overridable?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          key?: string;
          name?: string;
          description?: string;
          default_enabled?: boolean;
          is_tenant_overridable?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      item_branch_settings: {
        Row: {
          id: string;
          tenant_id: string;
          item_id: string;
          branch_id: string;
          is_available: boolean;
          in_stock: boolean;
          out_of_stock_until: string | null;
          price_override: number | null;
          sale_price_override: number | null;
          display_order: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          item_id: string;
          branch_id: string;
          is_available?: boolean;
          in_stock?: boolean;
          out_of_stock_until?: string | null;
          price_override?: number | null;
          sale_price_override?: number | null;
          display_order?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          item_id?: string;
          branch_id?: string;
          is_available?: boolean;
          in_stock?: boolean;
          out_of_stock_until?: string | null;
          price_override?: number | null;
          sale_price_override?: number | null;
          display_order?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "item_branch_settings_branch_id_fkey";
            columns: ["branch_id"];
            isOneToOne: false;
            referencedRelation: "branches";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "item_branch_settings_item_id_fkey";
            columns: ["item_id"];
            isOneToOne: false;
            referencedRelation: "items";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "item_branch_settings_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
        ];
      };
      item_modifier_groups: {
        Row: {
          tenant_id: string;
          item_id: string;
          modifier_group_id: string;
          display_order: number;
          is_required_override: boolean | null;
        };
        Insert: {
          tenant_id: string;
          item_id: string;
          modifier_group_id: string;
          display_order?: number;
          is_required_override?: boolean | null;
        };
        Update: {
          tenant_id?: string;
          item_id?: string;
          modifier_group_id?: string;
          display_order?: number;
          is_required_override?: boolean | null;
        };
        Relationships: [
          {
            foreignKeyName: "item_modifier_groups_item_id_fkey";
            columns: ["item_id"];
            isOneToOne: false;
            referencedRelation: "items";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "item_modifier_groups_modifier_group_id_fkey";
            columns: ["modifier_group_id"];
            isOneToOne: false;
            referencedRelation: "modifier_groups";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "item_modifier_groups_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
        ];
      };
      item_translations: {
        Row: {
          id: string;
          tenant_id: string;
          item_id: string;
          locale: string;
          name: string;
          description: string;
          ingredients: string;
          status: TranslationStatus;
          is_machine_generated: boolean;
          approved_at: string | null;
          approved_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          item_id: string;
          locale: string;
          name?: string;
          description?: string;
          ingredients?: string;
          status?: TranslationStatus;
          is_machine_generated?: boolean;
          approved_at?: string | null;
          approved_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          item_id?: string;
          locale?: string;
          name?: string;
          description?: string;
          ingredients?: string;
          status?: TranslationStatus;
          is_machine_generated?: boolean;
          approved_at?: string | null;
          approved_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "item_translations_approved_by_fkey";
            columns: ["approved_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "item_translations_item_id_fkey";
            columns: ["item_id"];
            isOneToOne: false;
            referencedRelation: "items";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "item_translations_locale_fkey";
            columns: ["locale"];
            isOneToOne: false;
            referencedRelation: "languages";
            referencedColumns: ["code"];
          },
          {
            foreignKeyName: "item_translations_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
        ];
      };
      items: {
        Row: {
          id: string;
          public_id: string;
          tenant_id: string;
          category_id: string | null;
          sku: string | null;
          base_price: number;
          sale_price: number | null;
          currency: string | null;
          image_path: string | null;
          image_url: string | null;
          gallery: Json;
          is_active: boolean;
          in_stock: boolean;
          out_of_stock_until: string | null;
          out_of_stock_reason: string | null;
          is_featured: boolean;
          is_new: boolean;
          is_popular: boolean;
          display_order: number;
          dietary_tags: string[];
          allergens: string[];
          spice_level: number | null;
          calories: number | null;
          preparation_time_minutes: number | null;
          service_duration_minutes: number | null;
          custom_attributes: Json;
          visible_from: string | null;
          visible_until: string | null;
          visibility_schedule: Json | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          public_id?: string;
          tenant_id: string;
          category_id?: string | null;
          sku?: string | null;
          base_price?: number;
          sale_price?: number | null;
          currency?: string | null;
          image_path?: string | null;
          image_url?: string | null;
          gallery?: Json;
          is_active?: boolean;
          in_stock?: boolean;
          out_of_stock_until?: string | null;
          out_of_stock_reason?: string | null;
          is_featured?: boolean;
          is_new?: boolean;
          is_popular?: boolean;
          display_order?: number;
          dietary_tags?: string[];
          allergens?: string[];
          spice_level?: number | null;
          calories?: number | null;
          preparation_time_minutes?: number | null;
          service_duration_minutes?: number | null;
          custom_attributes?: Json;
          visible_from?: string | null;
          visible_until?: string | null;
          visibility_schedule?: Json | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          public_id?: string;
          tenant_id?: string;
          category_id?: string | null;
          sku?: string | null;
          base_price?: number;
          sale_price?: number | null;
          currency?: string | null;
          image_path?: string | null;
          image_url?: string | null;
          gallery?: Json;
          is_active?: boolean;
          in_stock?: boolean;
          out_of_stock_until?: string | null;
          out_of_stock_reason?: string | null;
          is_featured?: boolean;
          is_new?: boolean;
          is_popular?: boolean;
          display_order?: number;
          dietary_tags?: string[];
          allergens?: string[];
          spice_level?: number | null;
          calories?: number | null;
          preparation_time_minutes?: number | null;
          service_duration_minutes?: number | null;
          custom_attributes?: Json;
          visible_from?: string | null;
          visible_until?: string | null;
          visibility_schedule?: Json | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "items_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "items_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "items_currency_fkey";
            columns: ["currency"];
            isOneToOne: false;
            referencedRelation: "currencies";
            referencedColumns: ["code"];
          },
          {
            foreignKeyName: "items_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
        ];
      };
      languages: {
        Row: {
          code: string;
          english_name: string;
          native_name: string;
          direction: string;
          is_enabled: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          code: string;
          english_name: string;
          native_name: string;
          direction?: string;
          is_enabled?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          code?: string;
          english_name?: string;
          native_name?: string;
          direction?: string;
          is_enabled?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      login_audit: {
        Row: {
          id: number;
          user_id: string | null;
          tenant_id: string | null;
          email: string;
          portal: string;
          was_successful: boolean;
          failure_reason: string | null;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: number;
          user_id?: string | null;
          tenant_id?: string | null;
          email: string;
          portal: string;
          was_successful: boolean;
          failure_reason?: string | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          user_id?: string | null;
          tenant_id?: string | null;
          email?: string;
          portal?: string;
          was_successful?: boolean;
          failure_reason?: string | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "login_audit_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "login_audit_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      media_assets: {
        Row: {
          id: string;
          public_id: string;
          tenant_id: string;
          bucket: string;
          path: string;
          url: string | null;
          kind: MediaKind;
          mime_type: string;
          size_bytes: number;
          width: number | null;
          height: number | null;
          alt_text: string;
          original_filename: string;
          checksum: string | null;
          uploaded_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          public_id?: string;
          tenant_id: string;
          bucket?: string;
          path: string;
          url?: string | null;
          kind?: MediaKind;
          mime_type: string;
          size_bytes: number;
          width?: number | null;
          height?: number | null;
          alt_text?: string;
          original_filename?: string;
          checksum?: string | null;
          uploaded_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          public_id?: string;
          tenant_id?: string;
          bucket?: string;
          path?: string;
          url?: string | null;
          kind?: MediaKind;
          mime_type?: string;
          size_bytes?: number;
          width?: number | null;
          height?: number | null;
          alt_text?: string;
          original_filename?: string;
          checksum?: string | null;
          uploaded_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "media_assets_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "media_assets_uploaded_by_fkey";
            columns: ["uploaded_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      modifier_group_translations: {
        Row: {
          id: string;
          tenant_id: string;
          modifier_group_id: string;
          locale: string;
          name: string;
          description: string;
          status: TranslationStatus;
          is_machine_generated: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          modifier_group_id: string;
          locale: string;
          name?: string;
          description?: string;
          status?: TranslationStatus;
          is_machine_generated?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          modifier_group_id?: string;
          locale?: string;
          name?: string;
          description?: string;
          status?: TranslationStatus;
          is_machine_generated?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "modifier_group_translations_locale_fkey";
            columns: ["locale"];
            isOneToOne: false;
            referencedRelation: "languages";
            referencedColumns: ["code"];
          },
          {
            foreignKeyName: "modifier_group_translations_modifier_group_id_fkey";
            columns: ["modifier_group_id"];
            isOneToOne: false;
            referencedRelation: "modifier_groups";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "modifier_group_translations_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
        ];
      };
      modifier_groups: {
        Row: {
          id: string;
          public_id: string;
          tenant_id: string;
          code: string;
          selection_type: ModifierSelection;
          is_required: boolean;
          min_selections: number;
          max_selections: number | null;
          display_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          public_id?: string;
          tenant_id: string;
          code: string;
          selection_type?: ModifierSelection;
          is_required?: boolean;
          min_selections?: number;
          max_selections?: number | null;
          display_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          public_id?: string;
          tenant_id?: string;
          code?: string;
          selection_type?: ModifierSelection;
          is_required?: boolean;
          min_selections?: number;
          max_selections?: number | null;
          display_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "modifier_groups_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
        ];
      };
      modifier_translations: {
        Row: {
          id: string;
          tenant_id: string;
          modifier_id: string;
          locale: string;
          name: string;
          status: TranslationStatus;
          is_machine_generated: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          modifier_id: string;
          locale: string;
          name?: string;
          status?: TranslationStatus;
          is_machine_generated?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          modifier_id?: string;
          locale?: string;
          name?: string;
          status?: TranslationStatus;
          is_machine_generated?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "modifier_translations_locale_fkey";
            columns: ["locale"];
            isOneToOne: false;
            referencedRelation: "languages";
            referencedColumns: ["code"];
          },
          {
            foreignKeyName: "modifier_translations_modifier_id_fkey";
            columns: ["modifier_id"];
            isOneToOne: false;
            referencedRelation: "modifiers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "modifier_translations_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
        ];
      };
      modifiers: {
        Row: {
          id: string;
          public_id: string;
          tenant_id: string;
          modifier_group_id: string;
          code: string;
          price_adjustment: number;
          is_default: boolean;
          is_active: boolean;
          in_stock: boolean;
          display_order: number;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          public_id?: string;
          tenant_id: string;
          modifier_group_id: string;
          code: string;
          price_adjustment?: number;
          is_default?: boolean;
          is_active?: boolean;
          in_stock?: boolean;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          public_id?: string;
          tenant_id?: string;
          modifier_group_id?: string;
          code?: string;
          price_adjustment?: number;
          is_default?: boolean;
          is_active?: boolean;
          in_stock?: boolean;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "modifiers_modifier_group_id_fkey";
            columns: ["modifier_group_id"];
            isOneToOne: false;
            referencedRelation: "modifier_groups";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "modifiers_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
        ];
      };
      offer_targets: {
        Row: {
          id: string;
          tenant_id: string;
          offer_id: string;
          target_type: OfferTargetType;
          item_id: string | null;
          category_id: string | null;
          branch_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          offer_id: string;
          target_type: OfferTargetType;
          item_id?: string | null;
          category_id?: string | null;
          branch_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          offer_id?: string;
          target_type?: OfferTargetType;
          item_id?: string | null;
          category_id?: string | null;
          branch_id?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "offer_targets_branch_id_fkey";
            columns: ["branch_id"];
            isOneToOne: false;
            referencedRelation: "branches";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "offer_targets_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "categories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "offer_targets_item_id_fkey";
            columns: ["item_id"];
            isOneToOne: false;
            referencedRelation: "items";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "offer_targets_offer_id_fkey";
            columns: ["offer_id"];
            isOneToOne: false;
            referencedRelation: "offers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "offer_targets_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
        ];
      };
      offer_translations: {
        Row: {
          id: string;
          tenant_id: string;
          offer_id: string;
          locale: string;
          name: string;
          description: string;
          status: TranslationStatus;
          is_machine_generated: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          offer_id: string;
          locale: string;
          name?: string;
          description?: string;
          status?: TranslationStatus;
          is_machine_generated?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          offer_id?: string;
          locale?: string;
          name?: string;
          description?: string;
          status?: TranslationStatus;
          is_machine_generated?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "offer_translations_locale_fkey";
            columns: ["locale"];
            isOneToOne: false;
            referencedRelation: "languages";
            referencedColumns: ["code"];
          },
          {
            foreignKeyName: "offer_translations_offer_id_fkey";
            columns: ["offer_id"];
            isOneToOne: false;
            referencedRelation: "offers";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "offer_translations_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
        ];
      };
      offers: {
        Row: {
          id: string;
          public_id: string;
          tenant_id: string;
          code: string;
          discount_type: DiscountType;
          discount_value: number;
          image_path: string | null;
          image_url: string | null;
          starts_at: string;
          ends_at: string | null;
          is_active: boolean;
          display_order: number;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          public_id?: string;
          tenant_id: string;
          code: string;
          discount_type: DiscountType;
          discount_value: number;
          image_path?: string | null;
          image_url?: string | null;
          starts_at?: string;
          ends_at?: string | null;
          is_active?: boolean;
          display_order?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          public_id?: string;
          tenant_id?: string;
          code?: string;
          discount_type?: DiscountType;
          discount_value?: number;
          image_path?: string | null;
          image_url?: string | null;
          starts_at?: string;
          ends_at?: string | null;
          is_active?: boolean;
          display_order?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "offers_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "offers_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
        ];
      };
      permissions: {
        Row: {
          key: string;
          category: string;
          description: string;
          is_destructive: boolean;
          sort_order: number;
        };
        Insert: {
          key: string;
          category: string;
          description?: string;
          is_destructive?: boolean;
          sort_order?: number;
        };
        Update: {
          key?: string;
          category?: string;
          description?: string;
          is_destructive?: boolean;
          sort_order?: number;
        };
        Relationships: [];
      };
      plans: {
        Row: {
          id: string;
          code: string;
          name: string;
          description: string;
          price_amount: number;
          price_currency: string;
          billing_period: string;
          duration_days: number;
          max_branches: number;
          max_categories: number;
          max_items: number;
          max_users: number;
          max_languages: number;
          max_storage_mb: number;
          features: Json;
          is_active: boolean;
          is_default: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          code: string;
          name: string;
          description?: string;
          price_amount?: number;
          price_currency?: string;
          billing_period?: string;
          duration_days?: number;
          max_branches?: number;
          max_categories?: number;
          max_items?: number;
          max_users?: number;
          max_languages?: number;
          max_storage_mb?: number;
          features?: Json;
          is_active?: boolean;
          is_default?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          code?: string;
          name?: string;
          description?: string;
          price_amount?: number;
          price_currency?: string;
          billing_period?: string;
          duration_days?: number;
          max_branches?: number;
          max_categories?: number;
          max_items?: number;
          max_users?: number;
          max_languages?: number;
          max_storage_mb?: number;
          features?: Json;
          is_active?: boolean;
          is_default?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "plans_price_currency_fkey";
            columns: ["price_currency"];
            isOneToOne: false;
            referencedRelation: "currencies";
            referencedColumns: ["code"];
          },
        ];
      };
      platform_settings: {
        Row: {
          key: string;
          value: Json;
          description: string;
          updated_by: string | null;
          updated_at: string;
        };
        Insert: {
          key: string;
          value: Json;
          description?: string;
          updated_by?: string | null;
          updated_at?: string;
        };
        Update: {
          key?: string;
          value?: Json;
          description?: string;
          updated_by?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "platform_settings_updated_by_fkey";
            columns: ["updated_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      platform_users: {
        Row: {
          id: string;
          user_id: string;
          email: string;
          full_name: string;
          role: PlatformRole;
          is_active: boolean;
          must_change_password: boolean;
          last_login_at: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          email: string;
          full_name?: string;
          role?: PlatformRole;
          is_active?: boolean;
          must_change_password?: boolean;
          last_login_at?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          email?: string;
          full_name?: string;
          role?: PlatformRole;
          is_active?: boolean;
          must_change_password?: boolean;
          last_login_at?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "platform_users_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: true;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      rate_limits: {
        Row: {
          bucket_key: string;
          window_started_at: string;
          hit_count: number;
          updated_at: string;
        };
        Insert: {
          bucket_key: string;
          window_started_at?: string;
          hit_count?: number;
          updated_at?: string;
        };
        Update: {
          bucket_key?: string;
          window_started_at?: string;
          hit_count?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      role_permissions: {
        Row: {
          role_id: string;
          permission_key: string;
        };
        Insert: {
          role_id: string;
          permission_key: string;
        };
        Update: {
          role_id?: string;
          permission_key?: string;
        };
        Relationships: [
          {
            foreignKeyName: "role_permissions_permission_key_fkey";
            columns: ["permission_key"];
            isOneToOne: false;
            referencedRelation: "permissions";
            referencedColumns: ["key"];
          },
          {
            foreignKeyName: "role_permissions_role_id_fkey";
            columns: ["role_id"];
            isOneToOne: false;
            referencedRelation: "roles";
            referencedColumns: ["id"];
          },
        ];
      };
      roles: {
        Row: {
          id: string;
          tenant_id: string | null;
          code: string;
          name: string;
          description: string;
          is_system: boolean;
          is_owner_role: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          tenant_id?: string | null;
          code: string;
          name: string;
          description?: string;
          is_system?: boolean;
          is_owner_role?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          tenant_id?: string | null;
          code?: string;
          name?: string;
          description?: string;
          is_system?: boolean;
          is_owner_role?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "roles_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
        ];
      };
      subscriptions: {
        Row: {
          id: string;
          tenant_id: string;
          plan_id: string;
          status: SubscriptionStatus;
          starts_at: string;
          expires_at: string;
          is_current: boolean;
          auto_renew: boolean;
          cancelled_at: string | null;
          notes: string;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          plan_id: string;
          status?: SubscriptionStatus;
          starts_at?: string;
          expires_at: string;
          is_current?: boolean;
          auto_renew?: boolean;
          cancelled_at?: string | null;
          notes?: string;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          plan_id?: string;
          status?: SubscriptionStatus;
          starts_at?: string;
          expires_at?: string;
          is_current?: boolean;
          auto_renew?: boolean;
          cancelled_at?: string | null;
          notes?: string;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "subscriptions_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "subscriptions_plan_id_fkey";
            columns: ["plan_id"];
            isOneToOne: false;
            referencedRelation: "plans";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "subscriptions_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: true;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
        ];
      };
      tenant_feature_flags: {
        Row: {
          tenant_id: string;
          flag_key: string;
          is_enabled: boolean;
          updated_by: string | null;
          updated_at: string;
        };
        Insert: {
          tenant_id: string;
          flag_key: string;
          is_enabled: boolean;
          updated_by?: string | null;
          updated_at?: string;
        };
        Update: {
          tenant_id?: string;
          flag_key?: string;
          is_enabled?: boolean;
          updated_by?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "tenant_feature_flags_flag_key_fkey";
            columns: ["flag_key"];
            isOneToOne: false;
            referencedRelation: "feature_flags";
            referencedColumns: ["key"];
          },
          {
            foreignKeyName: "tenant_feature_flags_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tenant_feature_flags_updated_by_fkey";
            columns: ["updated_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      tenant_user_permissions: {
        Row: {
          tenant_id: string;
          tenant_user_id: string;
          permission_key: string;
          effect: string;
          created_at: string;
        };
        Insert: {
          tenant_id: string;
          tenant_user_id: string;
          permission_key: string;
          effect: string;
          created_at?: string;
        };
        Update: {
          tenant_id?: string;
          tenant_user_id?: string;
          permission_key?: string;
          effect?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "tenant_user_permissions_permission_key_fkey";
            columns: ["permission_key"];
            isOneToOne: false;
            referencedRelation: "permissions";
            referencedColumns: ["key"];
          },
          {
            foreignKeyName: "tenant_user_permissions_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tenant_user_permissions_tenant_user_id_fkey";
            columns: ["tenant_user_id"];
            isOneToOne: false;
            referencedRelation: "tenant_users";
            referencedColumns: ["id"];
          },
        ];
      };
      tenant_users: {
        Row: {
          id: string;
          tenant_id: string;
          user_id: string;
          role_id: string;
          email: string;
          full_name: string;
          status: MembershipStatus;
          is_owner: boolean;
          must_change_password: boolean;
          branch_ids: string[];
          invited_by: string | null;
          invited_at: string | null;
          last_login_at: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          user_id: string;
          role_id: string;
          email: string;
          full_name?: string;
          status?: MembershipStatus;
          is_owner?: boolean;
          must_change_password?: boolean;
          branch_ids?: string[];
          invited_by?: string | null;
          invited_at?: string | null;
          last_login_at?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          user_id?: string;
          role_id?: string;
          email?: string;
          full_name?: string;
          status?: MembershipStatus;
          is_owner?: boolean;
          must_change_password?: boolean;
          branch_ids?: string[];
          invited_by?: string | null;
          invited_at?: string | null;
          last_login_at?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "tenant_users_invited_by_fkey";
            columns: ["invited_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tenant_users_role_id_fkey";
            columns: ["role_id"];
            isOneToOne: false;
            referencedRelation: "roles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tenant_users_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tenant_users_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      tenants: {
        Row: {
          id: string;
          public_id: string;
          slug: string;
          name: string;
          legal_name: string;
          business_type: BusinessType;
          template_id: string | null;
          logo_path: string | null;
          logo_url: string | null;
          contact_email: string | null;
          contact_phone: string | null;
          contact_whatsapp: string | null;
          website_url: string | null;
          address_line: string;
          city: string;
          country: string;
          timezone: string;
          default_locale: string;
          supported_locales: string[];
          default_currency: string;
          registered_at: string;
          account_status: AccountStatus;
          internal_notes: string;
          settings: Json;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          public_id?: string;
          slug: string;
          name: string;
          legal_name?: string;
          business_type?: BusinessType;
          template_id?: string | null;
          logo_path?: string | null;
          logo_url?: string | null;
          contact_email?: string | null;
          contact_phone?: string | null;
          contact_whatsapp?: string | null;
          website_url?: string | null;
          address_line?: string;
          city?: string;
          country?: string;
          timezone?: string;
          default_locale?: string;
          supported_locales?: string[];
          default_currency?: string;
          registered_at?: string;
          account_status?: AccountStatus;
          internal_notes?: string;
          settings?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          public_id?: string;
          slug?: string;
          name?: string;
          legal_name?: string;
          business_type?: BusinessType;
          template_id?: string | null;
          logo_path?: string | null;
          logo_url?: string | null;
          contact_email?: string | null;
          contact_phone?: string | null;
          contact_whatsapp?: string | null;
          website_url?: string | null;
          address_line?: string;
          city?: string;
          country?: string;
          timezone?: string;
          default_locale?: string;
          supported_locales?: string[];
          default_currency?: string;
          registered_at?: string;
          account_status?: AccountStatus;
          internal_notes?: string;
          settings?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "tenants_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tenants_default_currency_fkey";
            columns: ["default_currency"];
            isOneToOne: false;
            referencedRelation: "currencies";
            referencedColumns: ["code"];
          },
          {
            foreignKeyName: "tenants_default_locale_fkey";
            columns: ["default_locale"];
            isOneToOne: false;
            referencedRelation: "languages";
            referencedColumns: ["code"];
          },
          {
            foreignKeyName: "tenants_template_id_fkey";
            columns: ["template_id"];
            isOneToOne: false;
            referencedRelation: "business_templates";
            referencedColumns: ["id"];
          },
        ];
      };
      translation_jobs: {
        Row: {
          id: string;
          tenant_id: string;
          entity_type: string;
          entity_id: string;
          source_locale: string;
          target_locales: string[];
          status: TranslationJobStatus;
          provider: string;
          model: string | null;
          overwrite_approved: boolean;
          requested_by: string | null;
          started_at: string | null;
          completed_at: string | null;
          result: Json | null;
          error_message: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tenant_id: string;
          entity_type: string;
          entity_id: string;
          source_locale: string;
          target_locales: string[];
          status?: TranslationJobStatus;
          provider?: string;
          model?: string | null;
          overwrite_approved?: boolean;
          requested_by?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          result?: Json | null;
          error_message?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tenant_id?: string;
          entity_type?: string;
          entity_id?: string;
          source_locale?: string;
          target_locales?: string[];
          status?: TranslationJobStatus;
          provider?: string;
          model?: string | null;
          overwrite_approved?: boolean;
          requested_by?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          result?: Json | null;
          error_message?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "translation_jobs_requested_by_fkey";
            columns: ["requested_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "translation_jobs_source_locale_fkey";
            columns: ["source_locale"];
            isOneToOne: false;
            referencedRelation: "languages";
            referencedColumns: ["code"];
          },
          {
            foreignKeyName: "translation_jobs_tenant_id_fkey";
            columns: ["tenant_id"];
            isOneToOne: false;
            referencedRelation: "tenants";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      account_status: "active" | "suspended" | "archived";
      analytics_event_type:
        | "menu_view"
        | "category_view"
        | "item_view"
        | "search"
        | "language_change"
        | "offer_view"
        | "branch_view";
      business_type: "restaurant" | "cafe" | "salon" | "barbershop" | "custom";
      discount_type: "percentage" | "fixed_amount" | "promotional_price";
      media_kind: "image" | "logo" | "icon" | "gallery" | "document";
      membership_status: "invited" | "active" | "disabled";
      modifier_selection: "single" | "multiple";
      offer_target_type: "item" | "category" | "branch" | "all_items";
      platform_role: "super_admin" | "support" | "analyst";
      subscription_status:
        | "trial"
        | "active"
        | "expiring_soon"
        | "expired"
        | "suspended"
        | "cancelled";
      translation_job_status:
        "queued" | "running" | "completed" | "failed" | "cancelled";
      translation_status: "draft" | "ai_generated" | "reviewed" | "approved";
    };
    CompositeTypes: Record<string, never>;
  };
};

export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type TablesInsert<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];

export type AnalyticsEventsRow = Tables<"analytics_events">;
export type AuditLogsRow = Tables<"audit_logs">;
export type BranchesRow = Tables<"branches">;
export type BusinessSettingsRow = Tables<"business_settings">;
export type BusinessTemplatesRow = Tables<"business_templates">;
export type CategoriesRow = Tables<"categories">;
export type CategoryBranchesRow = Tables<"category_branches">;
export type CategoryTranslationsRow = Tables<"category_translations">;
export type CurrenciesRow = Tables<"currencies">;
export type FeatureFlagsRow = Tables<"feature_flags">;
export type ItemBranchSettingsRow = Tables<"item_branch_settings">;
export type ItemModifierGroupsRow = Tables<"item_modifier_groups">;
export type ItemTranslationsRow = Tables<"item_translations">;
export type ItemsRow = Tables<"items">;
export type LanguagesRow = Tables<"languages">;
export type LoginAuditRow = Tables<"login_audit">;
export type MediaAssetsRow = Tables<"media_assets">;
export type ModifierGroupTranslationsRow =
  Tables<"modifier_group_translations">;
export type ModifierGroupsRow = Tables<"modifier_groups">;
export type ModifierTranslationsRow = Tables<"modifier_translations">;
export type ModifiersRow = Tables<"modifiers">;
export type OfferTargetsRow = Tables<"offer_targets">;
export type OfferTranslationsRow = Tables<"offer_translations">;
export type OffersRow = Tables<"offers">;
export type PermissionsRow = Tables<"permissions">;
export type PlansRow = Tables<"plans">;
export type PlatformSettingsRow = Tables<"platform_settings">;
export type PlatformUsersRow = Tables<"platform_users">;
export type RateLimitsRow = Tables<"rate_limits">;
export type RolePermissionsRow = Tables<"role_permissions">;
export type RolesRow = Tables<"roles">;
export type SubscriptionsRow = Tables<"subscriptions">;
export type TenantFeatureFlagsRow = Tables<"tenant_feature_flags">;
export type TenantUserPermissionsRow = Tables<"tenant_user_permissions">;
export type TenantUsersRow = Tables<"tenant_users">;
export type TenantsRow = Tables<"tenants">;
export type TranslationJobsRow = Tables<"translation_jobs">;
